#ifndef CPP3_SMARTCALC_V2_0_1_SRC_MODEL_ARITHMETIC_CALCULATOR_VECTORS_NUMBERS_H_
#define CPP3_SMARTCALC_V2_0_1_SRC_MODEL_ARITHMETIC_CALCULATOR_VECTORS_NUMBERS_H_

#include "vector.h"

namespace s21 {
class Numbers : public Vector<double> {};
}  // namespace s21

#endif  // CPP3_SMARTCALC_V2_0_1_SRC_MODEL_ARITHMETIC_CALCULATOR_VECTORS_NUMBERS_H_
